INSERT INTO Jabatan (Jabatan_ID, Nama_Jabatan)
VALUES
(1, 'Owner'),
(2, 'General Manager'),
(3, 'Store Manager'),
(4, 'Assistant Manager'),
(5, 'Barista Head'),
(6, 'Senior Barista'),
(7, 'Barista'),
(8, 'Junior Barista'),
(9, 'Brew Master'),
(10, 'Shift Supervisor'),
(11, 'Cashier'),
(12, 'Waiter'),
(13, 'Procurement Specialist'),
(14, 'Host'),
(15, 'Marketing Manager'),
(16, 'Social Media Specialist'),
(17, 'Event Coordinator'),
(18, 'Graphic Designer'),
(19, 'Customer Service'),
(20, 'Maintenance Staff'),
(21, 'Cleaner'),
(22, 'Security'),
(23, 'Trainer'),
(24, 'Quality Control'),
(25, 'Dishwasher'),
(26, 'Recuitment Manager'),
(27, 'Financial Analyst'),
(28, 'Data Analyst'),
(29, 'Sustainability Manager'),
(30, 'Research & Development');

SELECT * FROM Jabatan;